# -*- coding: utf-8 -*-
"""Image Enhancement.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MiCIQ3YGl8iODhJm1MHz5vBpH60h7Mfr

# Setting Up
"""

!nvidia-smi

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/soumik12345/MIRNet
# %cd MIRNet

!pip install -q wandb

from glob import glob
from PIL import Image
from matplotlib import pyplot as plt
from mirnet.inference import Inferer
from mirnet.utils import download_dataset, plot_result

import tensorflow as tf
import numpy as np
print(tf.__version__)

inferer = Inferer()
inferer.download_weights('1sUlRD5MTRKKGxtqyYDpTv7T3jOW6aVAL')
inferer.build_model(
    num_rrg=3, num_mrb=2, channels=64,
    weights_path='low_light_weights_best.h5'
)

inferer.model.summary()

inferer.model.save('mirnet')

inferer.model.save('mirnet-save.h5')

"""# 256*256 Image"""

IMAGE_LOC = '/content/image3.jpg'

original_image, output_image = inferer.infer(IMAGE_LOC)
plot_result(original_image, output_image)

"""# On 128*128 image"""

IMAGE_LOC = '/content/image4.jpg'

original_image, output_image = inferer.infer(IMAGE_LOC)
plot_result(original_image, output_image)

"""# On 1600*1000"""

IMAGE_LOC = '/content/image5.jpg'

original_image, output_image = inferer.infer(IMAGE_LOC)
plot_result(original_image, output_image)

"""# On 1100*600"""

IMAGE_LOC = '/content/image6.JPEG'

original_image, output_image = inferer.infer(IMAGE_LOC)
plot_result(original_image, output_image)

IMAGE_LOC = '/content/image7.JPEG'
original_image, output_image = inferer.infer(IMAGE_LOC)
plot_result(original_image, output_image)

"""### By Sayan Nath"""